# Generated by Django 3.2.4 on 2021-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLongitude', models.TextField()),
                ('startLatitude', models.TextField()),
                ('endLongitude', models.TextField()),
                ('endLatitude', models.TextField()),
                ('startTime', models.TextField()),
                ('endTime', models.TextField()),
                ('date', models.TextField()),
                ('distanceTravelled', models.TextField()),
            ],
        ),
    ]
