# Generated by Django 3.2.4 on 2021-06-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20210629_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tripId',
        ),
    ]
