# Generated by Django 3.2.4 on 2021-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='department',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='jobPosition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='phoneNumber',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='transportationMethod',
            field=models.TextField(default=''),
        ),
    ]
