# Generated by Django 3.2.4 on 2021-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20210629_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
