# Generated by Django 3.2.4 on 2021-06-30 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0011_alter_trip_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
    ]
