# Generated by Django 3.2.4 on 2021-07-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_rename_member_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distanceTravelled',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='endTime',
        ),
    ]
