# Generated by Django 3.2.4 on 2021-07-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_auto_20210701_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
    ]
