# Generated by Django 3.2.4 on 2021-06-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210629_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
