# Generated by Django 3.2.4 on 2021-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_member_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='jobPosition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='transportationMethod',
            field=models.CharField(max_length=100),
        ),
    ]
